### ISSUE TITLE
[youtube:subscriptions] HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by Uddasa** [rg3/youtube-dl#2975]
Hi, since today (maybe yesterday) I got this error (the command was working well before) :

$ youtube-dl -o '/home/desktop/Vidéos/Youtube/%(uploader)s - %(title)s.%(ext)s' --download-archive /home/desktop/.mydownloads https://www.youtube.com/feed/subscriptions -u xxxxxxx@gmail.com -p xxxxxxxxx  --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-o', '/home/desktop/Vid\xc3\xa9os/Youtube/%(uploader)s - %(title)s.%(ext)s', '--download-archive', '/home/desktop/.mydownloads', 'https://www.youtube.com/feed/subscriptions', '-u', '<PRIVATE>', '-p', '<PRIVATE>', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.05.19
[debug] Python version 2.7.3 - Linux-3.10.23-xxxx-std-ipv6-64-x86_64-with-Ubuntu-12.04-precise
[debug] Proxy map: {}
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Logging in
[youtube:subscriptions] subscriptions feed: Downloading page 1
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 196, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1214, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by omeringen** [comment]
Hi,
I am experienceing HTTP Error 400 about ~3 days.
Restarted router, changed my DNS but no difference.

```
PS C:\WINDOWS\system32> F:\vid\youtube-dl.exe -U -v -u username -p pass -f "[height<=?800]" -o "F:\vid\%(upload_date)s.%(title)s.%(ext)s" https://www.youtube.com/playlist?list=WL
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', '[height<=?800]', '-o', 'F:\\vid\\%(upload_date)s.%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2019.04.17)
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\youtube.py", line 2927, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1tqz5pcu\build\youtube_dl\extractor\youtube.py", line 2439, in _extract_playlist
youtube_dl.utils.ExtractorError: This playlist does not exist.
```

```
PS C:\WINDOWS\system32> F:\vid\youtube-dl.exe -U -v -u 'username' -p 'pass' -f "[height<=?800]" -o "F:\vid\%(upload_date)s.%(title)s.%(ext)s" :ytsubs --dateafter 20190418
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', '[height<=?800]', '-o', 'F:\\vid\\%(upload_date)s.%(title)s.%(ext)s', ':ytsubs', '--dateafter', '20190418']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2019.04.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2019.04.17)
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Looking up account info
[youtube:subscriptions] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 0 videos
[download] Finished downloading playlist: Youtube Subscriptions
```

**Comment by omeringen** [comment]
Today's new build (2019.04.24) :
```
PS C:\WINDOWS\system32> F:\vid\youtube-dl.exe -U -v -u username -p pass -f "[height<=?800]" -o "F:\vi
d\%(upload_date)s.%(title)s.%(ext)s" :ytsubs --dateafter 20190418
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', '[height<=?800]', '-o', 'F:\\vid\\%(upload_date)s.%(title)s.%(ext)s', ':ytsubs', '--dateafter', '20190418']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2019.04.24)
[youtube:subscriptions] Downloading login page
[youtube:subscriptions] Looking up account info
[youtube:subscriptions] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 0 videos
[download] Finished downloading playlist: Youtube Subscriptions
```
```

PS C:\WINDOWS\system32> F:\vid\youtube-dl.exe -U -v -u username -p pass -f "[height<=?800]" -o "F:\vid\%(upload_date)s.%(title)s.%(ext)s" https://www.youtube.com/playlist?list=WL
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-U', '-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', '[height<=?800]', '-o', 'F:\\vid\\%(upload_date)s.%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=WL']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2019.04.24
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2019.04.24)
[youtube:watchlater] Downloading login page
[youtube:watchlater] Looking up account info
[youtube:watchlater] Logging in
WARNING: Unable to log in: HTTP Error 400: Bad Request
[youtube:watchlater] WL: Downloading webpage
ERROR: This playlist does not exist.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\youtube.py", line 2937, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp1l3rbf78\build\youtube_dl\extractor\youtube.py", line 2449, in _extract_playlist
youtube_dl.utils.ExtractorError: This playlist does not exist.

```

**Comment by Quaraxkad** [comment]
I also get HTTP 400 on log in...

> [debug] System config: []
> [debug] User config: []
> [debug] Custom config: []
> [debug] Command-line args: [':ytsubs', '-i', '-u', 'PRIVATE', '-p', 'PRIVATE', '--max-downloads', '1', '--skip-download', '-o', '%(title)s (%(upload_date)s)', '--proxy', '', '-j', '--verbose']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2019.04.24
> [debug] Python version 3.4.4 (CPython) - Windows-2008ServerR2-6.1.7601-SP1
> [debug] exe versions: none
> [debug] Proxy map: {}
> WARNING: Unable to log in: HTTP Error 400: Bad Request

**Comment by omeringen** [comment]
Only a small portion of users experience this bug ? Bugs are labelled as _duplicate_ of this bug but this bug is marked as _closed_. So this wont fix ? Any suggestions ?

**Comment by rautamiekka** [comment]
> Only a small portion of users experience this bug ? Bugs are labelled as _duplicate_ of this bug but this bug is marked as _closed_. So this wont fix ? Any suggestions ?

You didn't read the whole thread in detail. It says this was fixed in a commit and therefore closed, and was never reopened afterwards and then re-closed.

I tried and can't test this cuz I use the auth method where you've to click a button in an Android app to approve.

**Comment by Quaraxkad** [comment]
Two issue reports were immediately closed and marked as duplicate by @dstftw without so much as a comment, were *not* duplicates of this issue. They do both involve HTTP 400 errors, but are most definitely not the same bug.

These two reports were created and both closed prematurely, as the issue is not a duplicate of the one described in this thread:
https://github.com/ytdl-org/youtube-dl/issues/20814
https://github.com/ytdl-org/youtube-dl/issues/20755

**Comment by omeringen** [comment]
> 
> 
> Two issue reports were immediately closed and marked as duplicate by @dstftw without so much as a comment, were _not_ duplicates of this issue. They do both involve HTTP 400 errors, but are most definitely not the same bug.
> 
> These two reports were created and both closed prematurely, as the issue is not a duplicate of the one described in this thread:
> #20814
> #20755

Yeah this is why i am asking. If they are duplicates of this bug, why this one is still closed ? If they are not duplicates, why they are marked as duplicate ?

**Comment by omeringen** [comment]
@dstftw ,
Do you need any more info ?

**Comment by Mikeltxo15** [comment]
Hey, I'm the user who opened the first Issue, #20755 . I think we should be having this conversation on my bug report, or on #20814 , so as to draw attention that the issue is not the one described in this post, is not a duplicate and is not fixed. In the meantime I'm going to try to write a little script that somehow circunvents the problem, but it won't be able to access the Watch Later playlist so it'll inevitably have some problems.
