### ISSUE TITLE
[NBC] Site Broken

### ISSUE THREAD

**Issue by kkicher** [rg3/youtube-dl#7806]
**Videos from NBC seem to be broken. Was working yesterday, today I get the following error...
Just did and update with the same result.
Cheers!**

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.nbc.com/the-voice/episode-guide/season-9/live-semifinal-performances/924']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.06
[debug] Python version 2.7.6 - Linux-3.16.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[NBC] 924: Downloading webpage
[ThePlatform] guid: Downloading webpage
ERROR: Unable to extract smil url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 663, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/theplatform.py", line 210, in _real_extract
    webpage, 'smil url', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 584, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract smil url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and will be available in the next version of youtube-dl.

**Comment by kkicher** [comment]
OK thanks

**Comment by denisvlr** [comment]
It seems there are still issues with videos from ThePlatform player. Here are a few examples of failing urls:
```
youtube-dl http://www.nbc.com/shades-of-blue/video/fall-of-man/2980525#vc3076=1
youtube-dl http://player.theplatform.com/p/0L7ZPC/ztJiSNFd5ggr/embed/select/9TvMwq9DWGkD?siteSectionId=telemundo_shows_vod&autoPlay=true#playerurl=http%3A//www.telemundo.com/shows/al-rojo-vivo/videos/al-rojo-vivo/noticias/todo-listo-para-la-llegada-de-papa-francisco-mexico-1049531
```
Tested with the latest version as of today (2016.02.10).

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. add `-v` flag to your command line, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v http://www.youtube.com/watch?v=BaW_jenozKcj
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by denisvlr** [comment]
Sure:
```
$ youtube-dl "http://www.nbc.com/shades-of-blue/video/fall-of-man/2980525#vc3076=1" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.nbc.com/shades-of-blue/video/fall-of-man/2980525#vc3076=1', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.2.1, ffprobe 2.2.1
[debug] Proxy map: {}
[NBC] 2980525: Downloading webpage
[ThePlatform] guid: Downloading webpage
[ThePlatform] guid: Downloading SMIL data
[ThePlatform] guid: Downloading m3u8 information
[ThePlatform] guid: Downloading JSON metadata
[debug] Invoking downloader on u'https://nbcmpx-vh.akamaihd.net/i/video/646/159/160204_2980525_Fall_of_Man_mpx_,1696,1296,896,696,496,306,240,150,64,.mp4.csmil/index_0_av.m3u8?null=&id=AgBJ%2fKF2F9Q0BHlrvlY9BDZrBvzVcRcY%2ftGXYgynW%2fdrDci8yF4RMVWVg%2fgd2zm%2fjx2mpgEkDMwiMQ%3d%3d&hdntl=exp=1455406329~acl=%2fi%2fvideo%2f646%2f159%2f160204_2980525_Fall_of_Man_mpx_*~data=hdntl~hmac=f76949c09643d9a83de5b87dd55afe8bacbc7c96644aac9d6809969b607f7e06'
[download] Destination: Fall of Man-2980525.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=X78yyRVVKfyfZiqbpzE+Vg==
' -i 'https://nbcmpx-vh.akamaihd.net/i/video/646/159/160204_2980525_Fall_of_Man_mpx_,1696,1296,896,696,496,306,240,150,64,.mp4.csmil/index_0_av.m3u8?null=&id=AgBJ%2fKF2F9Q0BHlrvlY9BDZrBvzVcRcY%2ftGXYgynW%2fdrDci8yF4RMVWVg%2fgd2zm%2fjx2mpgEkDMwiMQ%3d%3d&hdntl=exp=1455406329~acl=%2fi%2fvideo%2f646%2f159%2f160204_2980525_Fall_of_Man_mpx_*~data=hdntl~hmac=f76949c09643d9a83de5b87dd55afe8bacbc7c96644aac9d6809969b607f7e06' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Fall of Man-2980525.mp4.part'
ffmpeg version 2.2.1 Copyright (c) 2000-2014 the FFmpeg developers
  built on May 31 2015 22:45:52 with Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.2.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-hardcoded-tables --enable-avresample --enable-vda --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libfaac --enable-libmp3lame --enable-libxvid
  libavutil      52. 66.100 / 52. 66.100
  libavcodec     55. 52.102 / 55. 52.102
  libavformat    55. 33.100 / 55. 33.100
  libavdevice    55. 10.100 / 55. 10.100
  libavfilter     4.  2.100 /  4.  2.100
  libavresample   1.  2.  0 /  1.  2.  0
  libswscale      2.  5.102 /  2.  5.102
  libswresample   0. 18.100 /  0. 18.100
  libpostproc    52.  3.100 / 52.  3.100
https://nbcmpx-vh.akamaihd.net/i/video/646/159/160204_2980525_Fall_of_Man_mpx_,1696,1296,896,696,496,306,240,150,64,.mp4.csmil/index_0_av.m3u8?null=&id=AgBJ%2fKF2F9Q0BHlrvlY9BDZrBvzVcRcY%2ftGXYgynW%2fdrDci8yF4RMVWVg%2fgd2zm%2fjx2mpgEkDMwiMQ%3d%3d&hdntl=exp=1455406329~acl=%2fi%2fvideo%2f646%2f159%2f160204_2980525_Fall_of_Man_mpx_*~data=hdntl~hmac=f76949c09643d9a83de5b87dd55afe8bacbc7c96644aac9d6809969b607f7e06: Protocol not found


ERROR: ffmpeg exited with code 1
  File "/usr/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/youtube_dl/__init__.py", line 411, in main
    _real_main(argv)
  File "/Library/Python/2.7/site-packages/youtube_dl/__init__.py", line 401, in _real_main
    retcode = ydl.download(all_urls)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 1693, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 747, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 1363, in process_video_result
    self.process_info(new_info)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 1625, in process_info
    success = dl(filename, info_dict)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 1567, in dl
    return fd.download(name, info)
  File "/Library/Python/2.7/site-packages/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/Library/Python/2.7/site-packages/youtube_dl/downloader/hls.py", line 79, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/Library/Python/2.7/site-packages/youtube_dl/downloader/common.py", line 156, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 541, in report_error
    self.trouble(error_message, tb)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 503, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

```
$ youtube-dl "http://player.theplatform.com/p/0L7ZPC/ztJiSNFd5ggr/embed/select/9TvMwq9DWGkD?siteSectionId=telemundo_shows_vod&autoPlay=true#playerurl=http%3A//www.telemundo.com/shows/al-rojo-vivo/videos/al-rojo-vivo/noticias/todo-listo-para-la-llegada-de-papa-francisco-mexico-1049531" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://player.theplatform.com/p/0L7ZPC/ztJiSNFd5ggr/embed/select/9TvMwq9DWGkD?siteSectionId=telemundo_shows_vod&autoPlay=true#playerurl=http%3A//www.telemundo.com/shows/al-rojo-vivo/videos/al-rojo-vivo/noticias/todo-listo-para-la-llegada-de-papa-francisco-mexico-1049531', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.2.1, ffprobe 2.2.1
[debug] Proxy map: {}
[ThePlatform] ztJiSNFd5ggr: Downloading SMIL data
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 354, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 1906, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by dstftw** [comment]
Update ffmpeg.

**Comment by denisvlr** [comment]
Ok thanks that was the issue for the first link.

The second one still fails with a 404 (while the video is correctly accessible on a browser):

```
$ youtube-dl "http://player.theplatform.com/p/0L7ZPC/ztJiSNFd5ggr/embed/select/9TvMwq9DWGkD" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://player.theplatform.com/p/0L7ZPC/ztJiSNFd5ggr/embed/select/9TvMwq9DWGkD', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.5 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[ThePlatform] ztJiSNFd5ggr: Downloading SMIL data
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/Library/Python/2.7/site-packages/youtube_dl/extractor/common.py", line 354, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Python/2.7/site-packages/youtube_dl/YoutubeDL.py", line 1906, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by denisvlr** [comment]
Any update on this? I'm still getting the same problem with the Platform videos such as this one:
http://player.theplatform.com/p/0L7ZPC/ztJiSNFd5ggr/embed/select/9TvMwq9DWGkD
(while it's appears on my browser). See stack trace in previous comment.

**Comment by yan12125** [comment]
Generated links are OK with http://link.theplatform.com/s/0L7ZPC/9TvMwq9DWGkD?mbr=true&switch=progressive while broken with http://link.theplatform.com/s/0L7ZPC/9TvMwq9DWGkD?mbr=true

Any ideas @remitamine? This time it's impossible to create a new extractor.

**Comment by remitamine** [comment]
> Generated links are OK with http://link.theplatform.com/s/0L7ZPC/9TvMwq9DWGkD?mbr=true&switch=progressive while broken with http://link.theplatform.com/s/0L7ZPC/9TvMwq9DWGkD?mbr=true

it similar to the other nbc network websites(usanetwork, syfy, bravo), they provide by default non working mp4 when the manifest requested without the correct query.
for free episodes there are valid mp4 files using `switch=http` or `switch=progressive`(depends on the website), and for full episodes and movies they provide m3u8 and f4m manifest(protected with akamai box) using `manifest=m3u` and `manifest=f4m`.
this is the same error in #10858.

> This time it's impossible to create a new extractor.

in this example url, it's possible to simply to transform the player url to link url.
`http://player.theplatform.com/p/0L7ZPC/ztJiSNFd5ggr/embed/select/9TvMwq9DWGkD` -> `http://link.theplatform.com/s/0L7ZPC/9TvMwq9DWGkD` but this doesn't work for all urls, see the example url in #10858.

**Comment by yan12125** [comment]
Thanks for the information. The rule to create possible queries is quite useful. I guess youtube-dl can try by adding additional queries if mere ```mbr=true``` returns no valid links.
