### ISSUE TITLE
udemy.com not working

### ISSUE THREAD

**Issue by maheshvante2015** [rg3/youtube-dl#8948]

**Comment by maheshvante2015** [comment]
C:\cource\test>youtube-dl -u XXX -p XXX "https://www.udemy.com/XXX/"
[udemy:course] Downloading login popup
[udemy:course] Logging in as XXX
[udemy:course] XXX: Downloading webpage
[udemy:course] XXX: Downloading course JSON
[udemy:course] 561828: Downloading course curriculum
[download] Downloading playlist: XXX
[udemy:course] playlist XXX : Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[udemy] Downloading login popup
[udemy] 3314652: Downloading webpage
[udemy] 3314652: Downloading lecture JSON
[udemy] 3314652: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\cource\test>youtube-dl -u XXX -p XXX "https://www.udemy.com/XXX/"
[udemy:course] Downloading login popup
[udemy:course] Logging in as XXX
[udemy:course] XXX: Downloading webpage
[udemy:course] XXX: Downloading course JSON
[udemy:course] 561828: Downloading course curriculum
[download] Downloading playlist: XXX
[udemy:course] playlist XXX : Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[udemy] Downloading login popup
[udemy] 3314652: Downloading webpage
[udemy] 3314652: Downloading lecture JSON
[udemy] 3314652: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\cource\test>youtube-dl -u XXX -p XXX "https://www.udemy.com/XXX/" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'https://www.udemy.com/XXX/', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as XXX
[udemy:course] XXX: Downloading webpage
[udemy:course] XXX: Downloading course JSON
[udemy:course] 561828: Downloading course curriculum
[download] Downloading playlist: XXX
[udemy:course] playlist XXX : Collected 10 video ids (downloading 10 of them)
[download] Downloading video 1 of 10
[udemy] Downloading login popup
[udemy] 3314652: Downloading webpage
[udemy] 3314652: Downloading lecture JSON
[udemy] 3314652: Downloading lecture JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: FORBIDDEN (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 365, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by jaan143** [comment]
i am also waiting the update plz Sir update it
thanks

**Comment by dstftw** [comment]
Works fine for me with the course from the test case (https://www.udemy.com/java-tutorial/).
1. Provide conctere example URL.
2. Provide the full verbose log.

**Comment by jaan143** [comment]
check it
PS C:\Users\HDNLUF037.WIN-IPDLDV1QL5B> youtube-dl --verbose -u ******@gmail.com -p ****** -o '~/MyVideos/%(pla
st)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/unity-touch-gestures-and-pathfinding-i
obile-unity-games/learn/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '~/MyVideos/%(playlist)s/%(chapter_n
er)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/unity-touch-gestures-and-pathfinding-in-mobile-unity-ga
/learn/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.02.09.1
[debug] Python version 3.4.3 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as ******@gmail.com
[udemy:course] unity-touch-gestures-and-pathfinding-in-mobile-unity-games: Downloading webpage
[udemy:course] unity-touch-gestures-and-pathfinding-in-mobile-unity-games: Downloading course JSON
[udemy:course] 761162: Downloading course curriculum
[download] Downloading playlist: Unity Touch Gestures and Pathfinding in Mobile Unity Games
[udemy:course] playlist Unity Touch Gestures and Pathfinding in Mobile Unity Games: Collected 22 video ids (downloadi
22 of them)
[download] Downloading video 1 of 22
[udemy] Downloading login popup
[udemy] 4617016: Downloading webpage
[udemy] 4617016: Downloading lecture JSON
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\youtube-dl.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\youtube_dl\__init__.py", line 411, in main
    _real_main(argv)
  File "C:\Python34\lib\site-packages\youtube_dl\__init__.py", line 401, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1690, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 837, in process_ie_result
    extra_info=extra)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 734, in process_ie_result
    extra_info=extra_info, download=False, process=False)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 315, in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\udemy.py", line 183, in _real_extract
    for format_ in asset.get('download_urls', {}).get('Video', []):
AttributeError: 'NoneType' object has no attribute 'get'
PS C:\Users\HDNLUF037.WIN-IPDLDV1QL5B>

**Comment by dstftw** [comment]
1. This is totally different error.
2. This course is not free. You have to provide account credentials or a free course URL reproducing the same error.

**Comment by jaan143** [comment]
but this course i enroll and i can watch lectures and everything and i downloaded many enroll courses before getting this error

**Comment by jaan143** [comment]
check this course also its free and getting same error
https://www.udemy.com/electric-bass-right-from-the-start/

**Comment by dstftw** [comment]
Fixed in ff9d5d093854a974afdd0191d331d817e7e4c2a7, f0e83681d97db52af9dc73d1c8e51d671503a222 and 5eb7db4ee96c97d98a87d8d7df46e8c6a607b682.

**Comment by maheshvante2015** [comment]
this code is working only for free courses..but for purchased courses still its not working

**Comment by dstftw** [comment]
Then you have to provide account credentials with purchased course.

**Comment by maheshvante2015** [comment]
C:\cource\test>youtube-dl -u --@gmail.com -p ... "https://www.udemy.com/sharepoint-2013-build-a-custom-ent-search-page-no-coding/learn/v4/content" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/sharepoint-2013-build-a-custom-ent-search-page-no-coding/learn/v4/content', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.18
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as --@gmail.com
[udemy:course] sharepoint-2013-build-a-custom-ent-search-page-no-coding: Downloading webpage
[udemy:course] sharepoint-2013-build-a-custom-ent-search-page-no-coding: Downloading course JSON
[udemy:course] 324838: Downloading course curriculum
[download] Downloading playlist: SharePoint 2013 - Build a custom Ent. Search Page, no coding
[udemy:course] playlist SharePoint 2013 - Build a custom Ent. Search Page, no coding: Collected 12 video ids (downloading 12 of them)
[download] Downloading video 1 of 12
[udemy] Downloading login popup
[udemy] 1826038: Downloading webpage
[udemy] 1826038: Downloading lecture JSON
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python3.5\lib\site-packages\youtube_dl\YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "c:\python3.5\lib\site-packages\youtube_dl\extractor\common.py", line 320, in extract
    return self._real_extract(url)
  File "c:\python3.5\lib\site-packages\youtube_dl\extractor\udemy.py", line 248, in _real_extract
    self._sort_formats(formats)
  File "c:\python3.5\lib\site-packages\youtube_dl\extractor\common.py", line 839, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by jaan143** [comment]
still getting same error with enroll courses and free courses also
PS C:\Users\vicky> youtube-dl --verbose -u ****@gmail.com -p **** -o '~/MyVideos/%(playlist)s/%(chapter_numbe
r)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/electric-bass-right-from-the-start/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/electric-bass-right-from-the-start/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as ****@gmail.com
[udemy:course] electric-bass-right-from-the-start: Downloading webpage
[udemy:course] electric-bass-right-from-the-start: Downloading course JSON
[udemy:course] 277770: Downloading course curriculum
[download] Downloading playlist: Electric Bass Right From The Start
[udemy:course] playlist Electric Bass Right From The Start: Collected 9 video ids (downloading 9 of them)
[download] Downloading video 1 of 9
[udemy] Downloading login popup
[udemy] 4580906: Downloading webpage
[udemy] 4580906: Downloading lecture JSON
[debug] Invoking downloader on 'http://knowband-asset-bucket.s3.amazonaws.com/2016-03-04_13-31-54-60a1590c65ee6323da7220abda8066da/WebHD_720p.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1624, in process_info
    success = dl(filename, info_dict)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1566, in dl
    return fd.download(name, info)
  File "C:\Python34\lib\site-packages\youtube_dl\downloader\common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "C:\Python34\lib\site-packages\youtube_dl\downloader\http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Python34\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "C:\Python34\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python34\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "C:\Python34\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "C:\Python34\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
